export const classesConstants = {
    GET_CLASSES_REQUEST: "GET_CLASSES_REQUEST",
    GET_CLASSES_SUCCESS: "GET_CLASSES_SUCCESS",
    GET_CLASSES_FAILURE: "GET_CLASSES_FAILURE",
  
  
    CLEAR_ERRORS: "CLEAR_ERRORS",
  };