export const sectionConstants = {
    GET_SECTION_REQUEST: "GET_SECTION_REQUEST",
    GET_SECTION_SUCCESS: "GET_SECTION_SUCCESS",
    GET_SECTION_FAILURE: "GET_SECTION_FAILURE",
  
  
    CLEAR_ERRORS: "CLEAR_ERRORS",
  };