export const studentsConstants = {
  GET_ALL_STUDENTS_REQUEST: "GET_ALL_STUDENTS_REQUEST",
  GET_ALL_STUDENTS_SUCCESS: "GET_ALL_STUDENTS_SUCCESS",
  GET_ALL_STUDENTS_FAILURE: "GET_ALL_STUDENTS_FAILURE",

  ADD_STUDENT_REQUEST: "ADD_STUDENT_REQUEST",
  ADD_STUDENT_SUCCESS: "ADD_STUDENT_SUCCESS",
  ADD_STUDENT_FAILURE: "ADD_STUDENT_FAILURE",

  UPDATE_STUDENT_REQUEST: "UPDATE_STUDENT_REQUEST",
  UPDATE_STUDENT_SUCCESS: "UPDATE_STUDENT_SUCCESS",
  UPDATE_STUDENT_FAILURE: "UPDATE_STUDENT_FAILURE",

  DELETE_STUDENT_REQUEST: "DELETE_STUDENT_REQUEST",
  DELETE_STUDENT_SUCCESS: "DELETE_STUDENT_SUCCESS",
  DELETE_STUDENT_FAILURE: "DELETE_STUDENT_FAILURE",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};